#!/usr/bin/env php
<?php
// +----------------------------------------------------------------------
// | 控制台入口（php think ...）
// +----------------------------------------------------------------------
namespace think;

require __DIR__ . '/vendor/autoload.php';

$app = new App();
$http = $app->http;

$console = new Console($app);
$console->run();
